# fly.toml app configuration file generated for maxi-nwl on 2023-07-14T12:11:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maxi-nwl"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
